name: Go Version Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.'
    - name: Prep modules
      run: |
        go mod init example.com/trash-levels && \
        go get github.com/gorilla/mux/ && \
        go get github.com/prometheus/client_golang/prometheus && \
        go get github.com/prometheus/client_golang/prometheus/promhttp
    - name: Build
      run: go build -v main.go
